export const GAME_TRANSLATIONS = {
  es: {
    backHome: "Volver al inicio",
    computerOnly: "⚠️ Debes jugar desde una computadora.",
    selectPlayers: "Selecciona cuántos jugadores se unirán:",
    connecting: "Conectando...",
    connected: "conectado",
    connect: "Conectar",
    start: "Iniciar",
    skip: "Saltar",
    deal: "Repartir",
    dealer: "Crupier",
    noMessages: "— Aún no hay mensajes —",
    typeMessage: "Escribe un mensaje...",
    send: "Enviar",
    match: "Partida",
  },
  en: {
    backHome: "Back to Home",
    computerOnly: "⚠️ You must play from a computer.",
    selectPlayers: "Select how many players will join:",
    connecting: "Connecting...",
    connected: "connected",
    connect: "Connect",
    start: "Start",
    skip: "Skip",
    deal: "Deal",
    dealer: "Dealer",
    noMessages: "— No messages yet —",
    typeMessage: "Type a message...",
    send: "Send",
    match: "Match",
  },
  pt: {
    backHome: "Voltar para o início",
    computerOnly: "⚠️ Você deve jogar de um computador.",
    selectPlayers: "Selecione quantos jogadores irão entrar:",
    connecting: "Conectando...",
    connected: "conectado",
    connect: "Conectar",
    start: "Iniciar",
    skip: "Pular",
    deal: "Distribuir",
    dealer: "Dealer",
    noMessages: "— Nenhuma mensagem ainda —",
    typeMessage: "Digite uma mensagem...",
    send: "Enviar",
    match: "Partida",
  },
} as const;
