export const HOME_TRANSLATIONS = {
  es: {
    description:
      "Un blackjack táctico donde las cartas no solo valen puntos, valen vidas. Apuesta, defiende, manipula probabilidades y destruye a tus rivales en partidas clasificadas en tiempo real.",
    secureSystem: "Sistema activo ∎ conexión segura con servidor maestro",
    player: "Jugador",
    alias: "Alias actual",
    serverStatus: "Estado del servidor",
    playersOnline: "jugadores conectados",
    mode: "Modo disponible",
    activeChannel: "Canal activo: Combate competitivo",
    pvpMode: "Multijugador PvP",
    startGame: "Iniciar partida",
    howToPlay: "Cómo jugar",
    settings: "Configuración",
    secureNode: "nodo seguro: canal cifrado ∎",
    hudSystem: "SISTEMA",
    hudNode: "NODE_21",
    hudEnergy: "ENERGÍA",
    hudStream: "● stream activo",
    hudData: "∎ datos sincronizados",
  },
  en: {
    description:
      "A tactical blackjack where cards don’t just score points — they decide fates. Bet, defend, manipulate odds, and crush rivals in real-time ranked matches.",
    secureSystem: "System active ∎ secure connection with master server",
    player: "Player",
    alias: "Current alias",
    serverStatus: "Server Status",
    playersOnline: "players online",
    mode: "Available Mode",
    activeChannel: "Active Channel: Competitive Combat",
    pvpMode: "Multiplayer PvP",
    startGame: "Start Game",
    howToPlay: "How to Play",
    settings: "Settings",
    secureNode: "secure node: encrypted channel ∎",
    hudSystem: "SYSTEM",
    hudNode: "NODE_21",
    hudEnergy: "ENERGY",
    hudStream: "● active stream",
    hudData: "∎ data synchronized",
  },
  pt: {
    description:
      "Um blackjack tático onde as cartas não apenas valem pontos — elas decidem destinos. Aposte, defenda, manipule probabilidades e derrote rivais em partidas classificadas em tempo real.",
    secureSystem: "Sistema ativo ∎ conexão segura com o servidor mestre",
    player: "Jogador",
    alias: "Apelido atual",
    serverStatus: "Status do servidor",
    playersOnline: "jogadores online",
    mode: "Modo disponível",
    activeChannel: "Canal ativo: Combate competitivo",
    pvpMode: "Multijogador PvP",
    startGame: "Iniciar partida",
    howToPlay: "Como jogar",
    settings: "Configurações",
    secureNode: "nó seguro: canal criptografado ∎",
    hudSystem: "SISTEMA",
    hudNode: "NODE_21",
    hudEnergy: "ENERGIA",
    hudStream: "● fluxo ativo",
    hudData: "∎ dados sincronizados",
  },
};
