export const TRANSLATIONS = {
  es: {
    title: "Configuración del Jugador",
    profile: "Perfil",
    fieldUsername: "Nombre de jugador",
    fieldLanguage: "Idioma",
    usernameHint: "Visible para otros jugadores. Máx. 24 caracteres.",
    audio: "Audio",
    volume: "Volumen general",
    music: "Música",
    sfx: "Efectos",
    audioHint: "Consejo: baja la música si necesitas concentrarte en las señales del juego.",
    chat: "Chat",
    chatEnable: "Activar chat",
    chatNotif: "Notificaciones de chat",
    notifHint: "Activa el chat para habilitar las notificaciones.",
    save: "Guardar cambios",
    saving: "Guardando...",
    back: "Volver al inicio",
    saved: "✓ Preferencias guardadas",
  },
  en: {
    title: "Player Settings",
    profile: "Profile",
    fieldUsername: "Player Name",
    fieldLanguage: "Language",
    usernameHint: "Visible to other players. Max 24 characters.",
    audio: "Audio",
    volume: "Master Volume",
    music: "Music",
    sfx: "Sound Effects",
    audioHint: "Tip: lower the music if you need to focus on game signals.",
    chat: "Chat",
    chatEnable: "Enable Chat",
    chatNotif: "Chat Notifications",
    notifHint: "Enable chat to allow notifications.",
    save: "Save Changes",
    saving: "Saving...",
    back: "Return to Home",
    saved: "✓ Preferences Saved",
  },
  pt: {
    title: "Configurações do Jogador",
    profile: "Perfil",
    fieldUsername: "Nome do jogador",
    fieldLanguage: "Idioma",
    usernameHint: "Visível para outros jogadores. Máx. 24 caracteres.",
    audio: "Áudio",
    volume: "Volume geral",
    music: "Música",
    sfx: "Efeitos sonoros",
    audioHint: "Dica: abaixe a música se precisar se concentrar nos sinais do jogo.",
    chat: "Chat",
    chatEnable: "Ativar chat",
    chatNotif: "Notificações de chat",
    notifHint: "Ative o chat para permitir notificações.",
    save: "Salvar alterações",
    saving: "Salvando...",
    back: "Voltar ao início",
    saved: "✓ Preferências salvas",
  },
};